[package]
name = "bstream"
version = "0.1.0"
authors = ["billettc <charles@cbillette.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = "0.4.3"